import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';
import assert from 'node:assert/strict';
const db=new PGlite({extensions:{pgcrypto}});
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create table auth.users(id uuid primary key,email text); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create schema storage; create table storage.buckets(id text primary key,name text, public boolean, file_size_limit bigint, allowed_mime_types text[]); create table storage.objects(id uuid, bucket_id text, name text);`);
let schema=fs.readFileSync(new URL('../supabase/schema.sql', import.meta.url),'utf8');
await db.exec(schema); await db.exec(schema);
await db.exec(`grant usage on schema public, auth to anon, authenticated, service_role; grant all on all tables in schema public to service_role;`);
await db.exec('set role service_role');
assert.equal((await db.query("select public.consume_request_limit('a',2,60) ok")).rows[0].ok,true);
assert.equal((await db.query("select public.consume_request_limit('a',2,60) ok")).rows[0].ok,true);
assert.equal((await db.query("select public.consume_request_limit('a',2,60) ok")).rows[0].ok,false);
await db.exec('reset role; set role anon');
await assert.rejects(()=>db.exec("insert into public.inquiries(name,email) values ('x','x@y.test')"));
await assert.rejects(()=>db.exec("select public.consume_request_limit('b',2,60)"));
await db.exec('reset role');
const summary=(await db.query("select public.analytics_summary(now()-interval '30 days') summary")).rows[0].summary;
assert.equal(summary.stats.events,0);
await db.exec("insert into public.visitor_events(event_type,session_id) select 'page_view', 'visitor-'||n from generate_series(1,1500) n");
const full = (await db.query("select public.analytics_summary(now()-interval '30 days') summary")).rows[0].summary;
assert.equal(full.stats.events,1500);
assert.equal(full.stats.uniqueVisitors,1500);
assert.equal(full.recent.length,30);
await db.exec("set role service_role; insert into public.inquiries(name,email,email_payload) values ('Buyer','buyer@example.test','{}'); reset role;");
assert.equal((await db.query("select count(*)::integer count from public.lead_email_jobs")).rows[0].count,1);
await db.exec("set role authenticated");
await assert.rejects(()=>db.exec("select public.mutate_category('create','test','{}')"));
await db.exec("reset role");
console.log('SQL snapshot repeated twice; role denials, atomic limits and empty analytics passed');
await db.close();
