export const COMPANY = {
  name: "GOPU Exports",
  legalName: "GOPU Exports Private Limited",
  email: "admin@gopuexports.com",
  phone: "+91 96189 91917",
  phoneHref: "tel:+919618991917",
  whatsapp: "https://wa.me/919618991917",
  founderPerson: "Bala Reddy Gopu",
  founderTitle: "Founder / Business Contact",
  contactPerson: "Sukesh Reddy",
  contactTitle: "Operations Manager",
  iec: "AAMCG8793P",
  cin: "U46909TS2026PTC212867",
  gst: "36AAMCG8793P1ZE",
  registeredAddress: "2nd Floor, Surya Arcade, Door No. 1-9-388, Kushaiguda Road, ECIL, Hyderabad – 500062, Telangana, India",
  hq: {
    label: "Headquarters (HQ)",
    address: "2nd Floor, Surya Arcade, Door No. 1-9-388, Kushaiguda Road, ECIL, Hyderabad – 500062, Telangana, India",
  },
  warehouse: {
    label: "GOPU Exports Factory & Warehouse",
    address: "Kanchanpally Village, Raghunathpally Mandal, Jangaon District – 506244, Telangana, India",
  },
  australia: {
    entityName: "GOPU GROUP PTY LTD",
    abn: "13 673 343 952",
    status: "Active from 04 Dec 2023",
    entityType: "Australian Private Company",
    location: "NSW 2010",
    note: "Australian entity details are publicly verifiable through ABN Lookup.",
    sourceUrl: "https://abr.business.gov.au/ABN/View?abn=13673343952",
  },
  verifiedIdentifiers: [
    { label: "IEC", value: "AAMCG8793P", status: "Verified" },
    { label: "CIN", value: "U46909TS2026PTC212867", status: "Verified" },
    { label: "GST", value: "36AAMCG8793P1ZE", status: "Verified" },
  ],
  pendingCertifications: [
    { label: "FSSAI", value: "Active", status: "License reference shared with verified buyers on request" },
  ],
  social: {
    linkedin: process.env.NEXT_PUBLIC_LINKEDIN_URL ?? "https://www.linkedin.com/company/gopu-exports/",
    facebook: process.env.NEXT_PUBLIC_FACEBOOK_URL ?? "https://www.facebook.com/search/top?q=gopu%20exports",
    instagram: process.env.NEXT_PUBLIC_INSTAGRAM_URL ?? "https://www.instagram.com/gopu_exports/",
  },
};
